-- FIX SUPABASE SCHEMA FOR FACTORYFLOW
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/gxeglfjlxdpcliptmunu/sql)

-- 1. Ensure Organizations table exists
CREATE TABLE IF NOT EXISTS public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT NOT NULL UNIQUE,
    organization_name TEXT NOT NULL,
    factory_name TEXT NOT NULL,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    radius_meters DOUBLE PRECISION DEFAULT 500,
    owner_username TEXT NOT NULL,
    owner_password TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Ensure Workers table has all required columns
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS pan_card TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS aadhar_card TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS mobile_number TEXT;

-- 3. Ensure other tables have organization_code
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.production_logs ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS organization_code TEXT;

-- 4. Ensure Production Logs has remarks column
ALTER TABLE public.production_logs ADD COLUMN IF NOT EXISTS remarks TEXT;

-- 5. Enable RLS (Optional but recommended, for now we ensure policies exist if enabled)
-- For this MVP, we want the 'workers' table to be readable by the anon key for login.
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for login" ON public.workers;
CREATE POLICY "Allow public read for login" ON public.workers FOR SELECT USING (true);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for org check" ON public.organizations;
CREATE POLICY "Allow public read for org check" ON public.organizations FOR SELECT USING (true);

-- Allow all operations for now to keep it simple (MVP)
DROP POLICY IF EXISTS "Allow all for anon" ON public.workers;
CREATE POLICY "Allow all for anon" ON public.workers ALL USING (true);

DROP POLICY IF EXISTS "Allow all for anon" ON public.production_logs;
CREATE POLICY "Allow all for anon" ON public.production_logs ALL USING (true);

DROP POLICY IF EXISTS "Allow all for anon" ON public.organizations;
CREATE POLICY "Allow all for anon" ON public.organizations ALL USING (true);

-- 6. Ensure owner_logs table exists for security tracking
CREATE TABLE IF NOT EXISTS public.owner_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT,
    login_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    device_name TEXT,
    os_version TEXT
);
ALTER TABLE public.owner_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for anon" ON public.owner_logs;
CREATE POLICY "Allow all for anon" ON public.owner_logs ALL USING (true);
