-- FIX SUPABASE SCHEMA FOR FACTORYFLOW
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/gxeglfjlxdpcliptmunu/sql)

-- 1. Ensure Organizations table exists
CREATE TABLE IF NOT EXISTS public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT NOT NULL UNIQUE,
    organization_name TEXT NOT NULL,
    factory_name TEXT NOT NULL,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    radius_meters DOUBLE PRECISION DEFAULT 500,
    owner_username TEXT NOT NULL,
    owner_password TEXT NOT NULL,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Ensure Workers table has all required columns
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS pan_card TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS aadhar_card TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS mobile_number TEXT;

-- 3. Ensure other tables have organization_code
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.production_logs ADD COLUMN IF NOT EXISTS organization_code TEXT;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS organization_code TEXT;

-- 4. Ensure Production Logs has remarks column
ALTER TABLE public.production_logs ADD COLUMN IF NOT EXISTS remarks TEXT;

-- 5. Enable RLS (MANDATORY for security)
-- For this MVP, we want the tables to be readable by the anon key for login and validation.
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_logs ENABLE ROW LEVEL SECURITY;

-- Workers policies
DROP POLICY IF EXISTS "Allow public read for login" ON public.workers;
CREATE POLICY "Allow public read for login" ON public.workers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow worker self access" ON public.workers;
CREATE POLICY "Allow worker self access" ON public.workers FOR ALL USING (
    (current_setting('request.jwt.claims', true)::jsonb ->> 'sub')::text = worker_id::text
);

-- Organizations policies
DROP POLICY IF EXISTS "Allow public read for org check" ON public.organizations;
CREATE POLICY "Allow public read for org check" ON public.organizations FOR SELECT USING (true);

-- Production Logs policies
DROP POLICY IF EXISTS "Allow all for anon" ON public.production_logs;
CREATE POLICY "Allow worker access to own logs" ON public.production_logs FOR ALL USING (
    (current_setting('request.jwt.claims', true)::jsonb ->> 'sub')::text = worker_id::text
);

-- Machines policies
DROP POLICY IF EXISTS "Allow all for anon" ON public.machines;
CREATE POLICY "Allow public read for machines" ON public.machines FOR SELECT USING (true);

-- Items policies
DROP POLICY IF EXISTS "Allow all for anon" ON public.items;
CREATE POLICY "Allow public read for items" ON public.items FOR SELECT USING (true);

-- Shifts policies
DROP POLICY IF EXISTS "Allow all for anon" ON public.shifts;
CREATE POLICY "Allow public read for shifts" ON public.shifts FOR SELECT USING (true);

-- Owner Logs policies
DROP POLICY IF EXISTS "Allow all for anon" ON public.owner_logs;
CREATE POLICY "Allow authenticated insert for owner logs" ON public.owner_logs FOR INSERT WITH CHECK (true);
