-- 1. Workers Table
CREATE TABLE IF NOT EXISTS workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Items Table
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  operations TEXT[] DEFAULT '{}',
  operation_details JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Machines Table
CREATE TABLE IF NOT EXISTS machines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'CNC' or 'VMC'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Production Logs Table
CREATE TABLE IF NOT EXISTS production_logs (
  id TEXT PRIMARY KEY, -- using UUID string from App
  worker_id TEXT NOT NULL,
  machine_id TEXT NOT NULL,
  item_id TEXT NOT NULL,
  operation TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  shift_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Shifts Table
CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) if needed, but for now we might keep it open for this MVP
-- ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
-- etc.
