-- Merged Login Logs and Supervisor Verification
-- 1. Login Logs
create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  worker_id text not null,
  role text not null,
  organization_code text,
  device_name text,
  os_version text,
  login_time timestamptz default now()
);

create index if not exists idx_login_logs_org on public.login_logs(organization_code);
create index if not exists idx_login_logs_worker on public.login_logs(worker_id);
create index if not exists idx_login_logs_time on public.login_logs(login_time desc);

-- 2. Workers Role
alter table public.workers add column if not exists role text default 'worker';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'workers_role_chk') then
    alter table public.workers add constraint workers_role_chk check (role in ('worker','supervisor'));
  end if;
end $$;

-- 3. Production Logs Verification
alter table public.production_logs add column if not exists is_verified boolean default false;
alter table public.production_logs add column if not exists verified_by text;
alter table public.production_logs add column if not exists verified_at timestamptz;
alter table public.production_logs add column if not exists verified_note text;
alter table public.production_logs add column if not exists supervisor_quantity integer;
