-- Track employee (worker/supervisor) logins
create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  worker_id text not null,
  role text not null,
  organization_code text,
  device_name text,
  os_version text,
  login_time timestamptz default now()
);

-- Optional indexes for faster admin queries
create index if not exists idx_login_logs_org on public.login_logs(organization_code);
create index if not exists idx_login_logs_worker on public.login_logs(worker_id);
create index if not exists idx_login_logs_time on public.login_logs(login_time desc);

