create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  organization_code text not null unique,
  organization_name text not null,
  factory_name text not null,
  address text,
  latitude double precision,
  longitude double precision,
  radius_meters double precision default 500,
  owner_username text not null,
  owner_password text not null
);

alter table public.workers add column if not exists organization_code text;
alter table public.machines add column if not exists organization_code text;
alter table public.items add column if not exists organization_code text;
alter table public.production_logs add column if not exists organization_code text;
alter table public.shifts add column if not exists organization_code text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'workers_org_code_fk') then
    alter table public.workers
      add constraint workers_org_code_fk foreign key (organization_code)
      references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'machines_org_code_fk') then
    alter table public.machines
      add constraint machines_org_code_fk foreign key (organization_code)
      references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'items_org_code_fk') then
    alter table public.items
      add constraint items_org_code_fk foreign key (organization_code)
      references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'production_logs_org_code_fk') then
    alter table public.production_logs
      add constraint production_logs_org_code_fk foreign key (organization_code)
      references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shifts_org_code_fk') then
    alter table public.shifts
      add constraint shifts_org_code_fk foreign key (organization_code)
      references public.organizations(organization_code) on delete cascade;
  end if;
end $$;
