-- Merged Base Multitenant and Shifts Migration
-- 1. Organizations
create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  organization_code text not null unique,
  organization_name text not null,
  factory_name text not null,
  address text,
  latitude double precision,
  longitude double precision,
  radius_meters double precision default 500,
  owner_username text not null,
  owner_password text not null
);

-- 2. Shifts
create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_time time,
  end_time time,
  organization_code text
);

insert into public.shifts(name, start_time, end_time)
select 'Morning', '07:30', '19:30'
where not exists (select 1 from public.shifts where name = 'Morning');

insert into public.shifts(name, start_time, end_time)
select 'Evening', '19:30', '07:30'
where not exists (select 1 from public.shifts where name = 'Evening');

-- 3. Workers
alter table public.workers add column if not exists organization_code text;
alter table public.workers add column if not exists current_shift text;

-- 4. Machines
alter table public.machines add column if not exists organization_code text;
update public.machines set type = 'CNC' where coalesce(type, '') not in ('CNC','VMC');

-- 5. Items
alter table public.items add column if not exists organization_code text;

-- 6. Production Logs
alter table public.production_logs add column if not exists organization_code text;
alter table public.production_logs add column if not exists shift_name text;

-- Constraints
do $$
begin
  -- Foreign Keys
  if not exists (select 1 from pg_constraint where conname = 'workers_org_code_fk') then
    alter table public.workers add constraint workers_org_code_fk foreign key (organization_code) references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'machines_org_code_fk') then
    alter table public.machines add constraint machines_org_code_fk foreign key (organization_code) references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'items_org_code_fk') then
    alter table public.items add constraint items_org_code_fk foreign key (organization_code) references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'production_logs_org_code_fk') then
    alter table public.production_logs add constraint production_logs_org_code_fk foreign key (organization_code) references public.organizations(organization_code) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shifts_org_code_fk') then
    alter table public.shifts add constraint shifts_org_code_fk foreign key (organization_code) references public.organizations(organization_code) on delete cascade;
  end if;
  
  -- Checks
  if not exists (select 1 from pg_constraint where conname = 'production_logs_shift_name_chk') then
    alter table public.production_logs add constraint production_logs_shift_name_chk check (shift_name in ('Morning','Evening'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'workers_current_shift_chk') then
    alter table public.workers add constraint workers_current_shift_chk check (current_shift in ('Morning','Evening'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'machines_type_chk') then
    alter table public.machines add constraint machines_type_chk check (type in ('CNC','VMC'));
  end if;
end $$;
