create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_time time,
  end_time time
);

insert into public.shifts(name, start_time, end_time)
values
  ('Morning', '07:30', '19:30'),
  ('Evening', '19:30', '07:30')
on conflict (name) do update
set start_time = excluded.start_time,
    end_time = excluded.end_time;

alter table public.production_logs
  add column if not exists shift_name text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'production_logs_shift_name_chk'
  ) then
    alter table public.production_logs
      add constraint production_logs_shift_name_chk
      check (shift_name in ('Morning','Evening'));
  end if;
end $$;

update public.production_logs pl
set shift_name = case
  when (pl."created_at" at time zone 'Asia/Kolkata')::time >= time '07:30'
       and (pl."created_at" at time zone 'Asia/Kolkata')::time < time '19:30'
    then 'Morning'
  else 'Evening'
end
where pl.shift_name is null;

create or replace function public.set_shift_name_if_null()
returns trigger language plpgsql as $$
begin
  if new.shift_name is null then
    if (new."created_at" at time zone 'Asia/Kolkata')::time >= time '07:30'
       and (new."created_at" at time zone 'Asia/Kolkata')::time < time '19:30'
    then
      new.shift_name := 'Morning';
    else
      new.shift_name := 'Evening';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists production_logs_set_shift_name on public.production_logs;
create trigger production_logs_set_shift_name
before insert on public.production_logs
for each row execute function public.set_shift_name_if_null();

alter table public.workers add column if not exists current_shift text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'workers_current_shift_chk'
  ) then
    alter table public.workers
      add constraint workers_current_shift_chk
      check (current_shift in ('Morning','Evening'));
  end if;
end $$;

update public.workers w
set current_shift = pl.shift_name
from (
  select distinct on (worker_id) worker_id, shift_name, "created_at"
  from public.production_logs
  where shift_name is not null
  order by worker_id, "created_at" desc
) pl
where pl.worker_id = w.worker_id
  and w.current_shift is null;

update public.machines
set type = 'CNC'
where coalesce(type, '') not in ('CNC','VMC');

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'machines_type_chk'
  ) then
    alter table public.machines
      add constraint machines_type_chk
      check (type in ('CNC','VMC'));
  end if;
end $$;
