-- STANDARDIZE TIMESTAMP HANDLING ACROSS ALL TABLES
-- This migration ensures all critical event tables use TIMESTAMP WITH TIME ZONE
-- and have DEFAULT NOW() to support "Backend as Truth" architecture.

-- 1. Create owner_logs if it doesn't exist (Security Logs)
CREATE TABLE IF NOT EXISTS public.owner_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT,
    device_name TEXT,
    os_version TEXT,
    login_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Ensure production_logs has correct columns and defaults
ALTER TABLE public.production_logs ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE public.production_logs 
    ALTER COLUMN timestamp SET DEFAULT NOW(),
    ALTER COLUMN created_at SET DEFAULT NOW();

-- 3. Ensure production_outofbounds has correct defaults
ALTER TABLE public.production_outofbounds 
    ALTER COLUMN exit_time SET DEFAULT NOW(),
    ALTER COLUMN created_at SET DEFAULT NOW();

-- 4. Ensure attendance has correct defaults
ALTER TABLE public.attendance 
    ALTER COLUMN check_in SET DEFAULT NOW(),
    ALTER COLUMN created_at SET DEFAULT NOW();

-- 5. Ensure worker_boundary_events has correct defaults
-- Check if table exists first as it's from a recent migration
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'worker_boundary_events') THEN
        ALTER TABLE public.worker_boundary_events 
            ALTER COLUMN created_at SET DEFAULT NOW();
    END IF;
END $$;

-- 6. Add indexes for faster time-based queries if they don't exist
CREATE INDEX IF NOT EXISTS idx_owner_logs_login_time ON public.owner_logs(login_time DESC);
CREATE INDEX IF NOT EXISTS idx_production_logs_timestamp ON public.production_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_check_in ON public.attendance(check_in DESC);
CREATE INDEX IF NOT EXISTS idx_outofbounds_exit_time ON public.production_outofbounds(exit_time DESC);
